apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Namespace
    metadata:
      name: $$NAME
      labels:
        name: $$NAME
  - apiVersion: apps/v1beta1
    kind: Deployment
    metadata:
      name: $$NAME-app
      namespace: $$NAME
      labels:
        name: $$NAME-app
        app: $$NAME
    spec:
      replicas: 1
      template:
        metadata:
          labels:
            name: $$NAME-app
            app: $$NAME
        spec:
          containers:
            - name: $$NAME-app
              image: hashicorp/http-echo
              args:
                - "-text=$$NAME"
  - apiVersion: v1
    kind: Service
    metadata:
      name: $$NAME-service
      namespace: $$NAME
    spec:
      selector:
        app: $$NAME
      ports:
        - name: app
          port: 5678 # Default port for image

  - apiVersion: extensions/v1beta1
    kind: Ingress
    metadata:
      name: $$NAME-ingress
      namespace: $$NAME
      annotations:
        ingress.kubernetes.io/rewrite-target: /
    spec:
      rules:
      - host: sdh-k8s.suse.ru
        http:
          paths:
            - path: /$$NAME
              backend:
                serviceName: $$NAME-service
                servicePort: 5678
