---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
 name: shop-ingress
 annotations:
   nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: sdh.suse.ru
    http:
      paths:
        - path: /shop
          backend:
            serviceName: front-end
            servicePort: 80
